client_config_backend: settings
client_config:
  client_id: 87596615353-qd3qc28ujq6ebd32qr1ptubv6nclii58.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: sumgpt/pydrive/credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install