# Generated by Django 4.2.8 on 2023-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sumgpt', '0002_sum'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='word_cloud')),
            ],
        ),
    ]
