# Generated by Django 4.2.8 on 2023-12-19 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sumgpt', '0003_wordcloud_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCloud_m',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField()),
                ('image', models.ImageField(upload_to='word_cloud')),
                ('sum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_cloud', to='sumgpt.sum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
