# Generated by Django 4.2.5 on 2023-10-26 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumgpt', '0003_sum_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='user',
        ),
        migrations.AddField(
            model_name='doc',
            name='sum',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='sumgpt.sum'),
        ),
    ]
