# Generated by Django 4.2.8 on 2024-01-17 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sumgpt', '0004_remove_doc_user_doc_sum'),
        ('sumgpt', '0004_wordcloud_m'),
    ]

    operations = [
    ]
