# Generated by Django 4.2.4 on 2024-01-17 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sumgpt', '0005_merge_0004_remove_doc_user_doc_sum_0004_wordcloud_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='sum',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sumgpt.sum'),
        ),
    ]
